/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.ConnectionF;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Admin
 */
public class LichChoThue extends javax.swing.JFrame {

    /**
     * Creates new form LichChoThue
     */
    private Connection con;
    private ResultSet rs;
    private PreparedStatement stmt;

    public void comboBox1() {
        String sql = "SELECT TenLoai from loaixe";
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery();
            while (rs.next()) {
                jComboBox2.addItem(rs.getString("TenLoai"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(LichChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("in ra combobox");
    }

    public void comboBox2() {
        String sql = "SELECT TenKH from khachhang";
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("TenKH"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(LichChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("in ra combobox");
    }

    public void showCar() {
        //System.out.println("Tao vector");
        //tao ten cot
        Vector cols = new Vector();
        cols.addElement("STT");
        cols.addElement("Khách hàng");
        cols.addElement("Ngày Đăng ký");
        cols.addElement("Ngày cho thuê");
        cols.addElement("Số ngày thuê");
        cols.addElement("Loại xe");

        //tao vector du lieu
        Vector data = new Vector();

        String sql = "SELECT lichchothue.STT,lichchothue.MaKH,lichchothue.MaLoai,lichchothue.NgayDK,lichchothue.NgayThue,lichchothue.SoNgayThue,khachhang.TenKH, loaixe.tenloai  FROM lichchothue, khachhang, loaixe where khachhang.MaKH = lichchothue.MaKH and lichchothue.MaLoai = loaixe.MaLoai;";
        //System.out.println("ket noi bang");

        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery();
            while (rs.next()) {
                Vector car = new Vector();
                car.addElement(rs.getString("lichchothue.STT"));
                car.addElement(rs.getString("khachhang.TenKH"));
                car.addElement(rs.getString("lichchothue.NgayDK"));
                car.addElement(rs.getString("lichchothue.NgayThue"));
                car.addElement(rs.getString("lichchothue.SoNgayThue"));
                car.addElement(rs.getString("loaixe.Tenloai"));
                data.add(car);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LichChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblCar.setModel(new DefaultTableModel(data, cols));
    }

    public LichChoThue() {
        initComponents();
        try {
            con = ConnectionF.getConnection();
        } catch (Exception e) {
            System.out.println("Kết nối bảng Xe bị lỗi");
        }
        showCar();
        comboBox1();
        comboBox2();
        System.out.println("Contructor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNgayDK = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayChoThue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSongay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car-icon.png"))); // NOI18N
        jLabel1.setText("Quản lý thông tin xe");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(8, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STT");
        jPanel3.add(jLabel2);
        jPanel3.add(txtID);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Khách hàng");
        jPanel3.add(jLabel3);

        jPanel3.add(jComboBox1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày đăng ký");
        jPanel3.add(jLabel4);

        txtNgayDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDKActionPerformed(evt);
            }
        });
        jPanel3.add(txtNgayDK);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ngày thuê");
        jPanel3.add(jLabel5);

        txtNgayChoThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayChoThueActionPerformed(evt);
            }
        });
        jPanel3.add(txtNgayChoThue);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Số ngày thuê");
        jPanel3.add(jLabel7);

        txtSongay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSongayActionPerformed(evt);
            }
        });
        jPanel3.add(txtSongay);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Loại xe");
        jPanel3.add(jLabel6);

        jPanel3.add(jComboBox2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert-icon.png"))); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-icon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-icon.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh-icon.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID xe", "Tên hãng xe", "Số chỗ", "Màu xe", "Đời xe", "Giá thành", "Dịch vụ", "Ngày giao dịch"
            }
        ));
        tblCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCar);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(64, 64, 64))
                            .addComponent(txtSearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel3.getAccessibleContext().setAccessibleName("\"I\"");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // Button Insert
        String sql = "insert into lichchothue(STT,MaKH,NgayDK,NgayThue,SoNgayThue,MaLoai) values(?,(select MaKH from khachhang where TenKH = ?),?,?,?,(select MaLoai from loaixe where TenLoai = ?))";
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, txtID.getText());
            stmt.setString(2, jComboBox1.getSelectedItem().toString());
            stmt.setString(3, txtNgayDK.getText());
            stmt.setString(4, txtNgayChoThue.getText());
            stmt.setString(5, txtSongay.getText());
            stmt.setString(6, jComboBox2.getSelectedItem().toString());
            stmt.executeUpdate();
            System.out.println("Da them thong tin xe");
            JOptionPane.showMessageDialog(this, "Thêm xe thành công !!! ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi thêm thông tin");
            Logger.getLogger(LichChoThue.class.getName()).log(Level.SEVERE, null, ex);

        }
        showCar();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Button Update
        String sql = "UPDATE lichchothue SET MaKH = (select MaKH from khachhang where TenKH = ?),NgayDK=?,NgayThue=?,SoNgayThue=?,MaLoai= (select MaLoai from loaixe where TenLoai = ?) WHERE STT=?";
        //String id = txtID.getText();
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(6, txtID.getText());
            stmt.setString(1, jComboBox1.getSelectedItem().toString());
            stmt.setString(2, txtNgayDK.getText());
            stmt.setString(3, txtNgayChoThue.getText());
            stmt.setString(4, txtSongay.getText());
            stmt.setString(5, jComboBox2.getSelectedItem().toString());
            stmt.executeUpdate();
            System.out.println("Da thay doi thong tin xe!");
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin xe thành công !!! ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy xa khi chỉnh sửa thông tin xe!");
            Logger.getLogger(LichChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }
        showCar();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //Button Delete
        String sql = "DELETE FROM lichchothue WHERE STT=?";
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin đang chọn ?");
        if (choice == JOptionPane.YES_OPTION) {
            try {
                //String id = txtID.getText();
                stmt = con.prepareStatement(sql);
                stmt.setString(1, txtID.getText());
                stmt.executeUpdate();
                System.out.println("Đã xóa thông tin xe bạn muốn");
                JOptionPane.showMessageDialog(this, "Xóa thành công !!! ");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi xóa");
                System.out.println(ex);
            }
        }
        showCar();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // button Refresh
        showCar();
        txtID.setText(null);
        // txtTenKH.setText(null);
        //txtSongay.setText(null);
        txtNgayDK.setText(null);
        txtNgayChoThue.setText(null);

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainMenu m = new MainMenu();
        m.setVisible(true);
        this.setVisible(false);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarMouseClicked
        // Mouse click table event
        int row = tblCar.getSelectedRow();
        if (row != -1) {
            txtID.setText(tblCar.getValueAt(row, 0).toString());
            jComboBox1.addItem(tblCar.getValueAt(row, 1).toString());
            txtNgayDK.setText(tblCar.getValueAt(row, 2).toString());
            // jComboBox1.setSelectedItem(tblCar.getValueAt(row, 3).toString());
            txtNgayChoThue.setText(tblCar.getValueAt(row, 3).toString());
            txtSongay.setText(tblCar.getValueAt(row, 4).toString());
            jComboBox2.addItem(tblCar.getValueAt(row, 5).toString());

            // jComboBox2.setSelectedItem(tblCar.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_tblCarMouseClicked
    public void SearchCar() {
        Vector cols = new Vector();
        cols.addElement("Số Xe");
        cols.addElement("Tên Xe");
        cols.addElement("Phí Xăng");
        cols.addElement("Phí Quá Km");
        cols.addElement("Đơn Giá ");
        cols.addElement("Mô Tả");
        cols.addElement("Trạng Thái");
        Vector data = new Vector();
        String textSearchCar = txtSearch.getText().trim();
        String sql = "SELECT * FROM xe";
        //System.out.println("ket noi bang");
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery();
            while (rs.next()) {
                Vector car = new Vector();
                car.addElement(rs.getString("SoXe"));
                car.addElement(rs.getString("TenXe"));
                car.addElement(rs.getString("PhiXang"));
                car.addElement(rs.getString("PhiQuaKm"));
                car.addElement(rs.getString("DonGia"));
                car.addElement(rs.getString("MoTaTT"));
                car.addElement(rs.getString("TrangThai"));
                if (car.toString().toUpperCase().contains(textSearchCar.toUpperCase())) {
                    data.add(car);
                }
            }
        } catch (SQLException ex) {
//            Logger.getLogger(LichChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblCar.setModel(new DefaultTableModel(data, cols));
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SearchCar();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtNgayChoThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayChoThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayChoThueActionPerformed

    private void txtNgayDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDKActionPerformed

    private void txtSongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSongayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSongayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichChoThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichChoThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichChoThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichChoThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichChoThue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCar;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNgayChoThue;
    private javax.swing.JTextField txtNgayDK;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSongay;
    // End of variables declaration//GEN-END:variables
}
